/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package insurance;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author T-PC
 */
public class AgentView extends javax.swing.JFrame {

    /**
     * Creates new form AgentView
     */
     Connection conn = null;
    PreparedStatement pst = null;
   
    ResultSet rs = null;
    public AgentView() {
        initComponents();
         conn=dbConnection.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAgentId = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldfname5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldfname9 = new javax.swing.JTextField();
        jTextFieldfname10 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldfname11 = new javax.swing.JTextField();
        jTextFieldfname12 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldfname13 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldfname14 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldfname15 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldpolName1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldpolAmount1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldpolTerm1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextFieldfaceAmount1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldinterest1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldbonusPeriod1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextFieldBonusRate1 = new javax.swing.JTextField();
        jLabeldate = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCusPayDetails = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelShowData = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCusDetails = new javax.swing.JTable();
        jLabelShowData1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSearch1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 153, 153));

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agent View: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMin)
                    .addComponent(jLabelClose)
                    .addComponent(jLabel3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Agent  ID      :");

        jTextFieldAgentId.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldAgentId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAgentId.setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(44, 62, 80));
        jPanel5.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Policy ID  :");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(460, 40, 90, 17);

        jTextFieldfname5.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname5);
        jTextFieldfname5.setBounds(560, 40, 150, 23);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Agent  ID      :");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(770, 40, 100, 17);

        jTextFieldfname9.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname9);
        jTextFieldfname9.setBounds(880, 40, 150, 23);

        jTextFieldfname10.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname10);
        jTextFieldfname10.setBounds(560, 110, 160, 23);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Policy Type :");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(440, 110, 100, 17);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Nominee   :");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(120, 170, 110, 17);

        jTextFieldfname11.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname11);
        jTextFieldfname11.setBounds(250, 170, 150, 23);

        jTextFieldfname12.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname12);
        jTextFieldfname12.setBounds(250, 230, 150, 23);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Relation  :");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(120, 230, 110, 17);

        jTextFieldfname13.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname13);
        jTextFieldfname13.setBounds(250, 300, 150, 23);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Address  :");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(120, 300, 100, 17);

        jButton3.setBackground(new java.awt.Color(0, 139, 195));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Create");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(282, 435, 79, 25);

        jButton4.setBackground(new java.awt.Color(255, 51, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cancel");
        jPanel5.add(jButton4);
        jButton4.setBounds(134, 435, 77, 25);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Customer NIC");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(99, 42, 124, 17);

        jTextFieldfname14.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname14);
        jTextFieldfname14.setBounds(227, 39, 150, 23);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Finduser.png"))); // NOI18N
        jPanel5.add(jLabel27);
        jLabel27.setBounds(1040, 40, 30, 30);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Finduser.png"))); // NOI18N
        jPanel5.add(jLabel28);
        jLabel28.setBounds(395, 32, 30, 30);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Finduser.png"))); // NOI18N
        jPanel5.add(jLabel29);
        jLabel29.setBounds(730, 30, 30, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Customer Name");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(120, 110, 124, 17);

        jTextFieldfname15.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname15);
        jTextFieldfname15.setBounds(250, 110, 150, 23);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Policy Name:");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(440, 150, 88, 17);

        jTextFieldpolName1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldpolName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldpolName1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldpolName1);
        jTextFieldpolName1.setBounds(560, 150, 160, 23);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Policy Amount:");
        jPanel5.add(jLabel32);
        jLabel32.setBounds(440, 230, 130, 17);

        jTextFieldpolAmount1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldpolAmount1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldpolAmount1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldpolAmount1);
        jTextFieldpolAmount1.setBounds(560, 190, 160, 23);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Policy Term:");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(440, 190, 84, 17);

        jTextFieldpolTerm1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldpolTerm1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldpolTerm1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldpolTerm1);
        jTextFieldpolTerm1.setBounds(560, 230, 160, 23);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Face Amount   :");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(440, 270, 108, 17);

        jTextFieldfaceAmount1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfaceAmount1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfaceAmount1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfaceAmount1);
        jTextFieldfaceAmount1.setBounds(560, 270, 160, 23);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Interest   :");
        jPanel5.add(jLabel35);
        jLabel35.setBounds(440, 310, 74, 17);

        jTextFieldinterest1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldinterest1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldinterest1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldinterest1);
        jTextFieldinterest1.setBounds(560, 310, 160, 23);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Bonus Period  :");
        jPanel5.add(jLabel36);
        jLabel36.setBounds(440, 350, 105, 17);

        jTextFieldbonusPeriod1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldbonusPeriod1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldbonusPeriod1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldbonusPeriod1);
        jTextFieldbonusPeriod1.setBounds(560, 350, 160, 23);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Bonus Rate  :");
        jPanel5.add(jLabel37);
        jLabel37.setBounds(440, 390, 93, 17);

        jTextFieldBonusRate1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldBonusRate1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBonusRate1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldBonusRate1);
        jTextFieldBonusRate1.setBounds(560, 390, 160, 23);

        jLabeldate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabeldate.setForeground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        jTableCusPayDetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableCusPayDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "Updtaed Terms", "Current Pay", "Pay Date"
            }
        ));
        jScrollPane3.setViewportView(jTableCusPayDetails);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Nic");

        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelShowData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelShowData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelShowData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-show-property-24.png"))); // NOI18N
        jLabelShowData.setText("Show Data");
        jLabelShowData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabelShowData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelShowDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelShowDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelShowDataMouseExited(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancel.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelShowData)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addGap(58, 58, 58)
                                .addComponent(jButton1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelShowData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Payment Details", jPanel3);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jTableCusDetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableCusDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "Agent ID", "Policy type", "Address", "Customer Name", "Policy Name", "Policy Amount", "Policy Term", "Face Amount", "Available Terms", "Current Pay Amount", "Reg Date", "End Date"
            }
        ));
        jScrollPane2.setViewportView(jTableCusDetails);

        jLabelShowData1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelShowData1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelShowData1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-show-property-24.png"))); // NOI18N
        jLabelShowData1.setText("Show Data");
        jLabelShowData1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabelShowData1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelShowData1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelShowData1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelShowData1MouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Nic");

        jTextFieldSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearch1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Search.png"))); // NOI18N
        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 51, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancel.png"))); // NOI18N
        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelShowData1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jTextFieldSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabelShowData1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Customer Details", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Your Agent ID Here ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jTabbedPane1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabeldate, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAgentId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAgentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(53, 53, 53)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(jLabeldate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabelShowDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelShowDataMouseClicked
        // TODO add your handling code here:
        String sql="select * from payment where aId=?";
        String search =jTextFieldAgentId.getText();
        try {
            pst=conn.prepareStatement(sql);
            pst.setString(1,search);
            rs =pst.executeQuery();

            while(rs.next()){
                String nic=String.valueOf(rs.getInt("nic"));
                String upTerm=String.valueOf(rs.getInt("updatedTerm"));
                String curreAmount=String.valueOf(rs.getDouble("currentAmount"));
                String payDate=rs.getString("payDate");
                
                String tbData[] = {nic,upTerm,curreAmount,payDate};

                DefaultTableModel tblModel = (DefaultTableModel)jTableCusPayDetails.getModel();

                tblModel.addRow(tbData);

            }

        } catch (SQLException ex) {
            Logger.getLogger(AgentView.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jLabelShowDataMouseClicked

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTableCusDetails.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tblModel);
        jTableCusDetails.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(jTextFieldSearch.getText().trim()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabelShowDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelShowDataMouseEntered
        // TODO add your handling code here:
        jLabelShowData.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelShowDataMouseEntered

    private void jLabelShowDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelShowDataMouseExited
        // TODO add your handling code here:
        jLabelShowData.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelShowDataMouseExited

    private void jLabelShowData1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelShowData1MouseClicked
        // TODO add your handling code here:
   
            String query="select * from CustomerPolicy where aId=?";
            String search =jTextFieldAgentId.getText();
            
        
           
        try {
            pst=conn.prepareStatement(query);
            pst.setString(1,search);
            rs =pst.executeQuery();
         

            while(rs.next()){
                String nic=String.valueOf(rs.getInt("nic"));
                String aid=rs.getString("aId");
                String poltype=rs.getString("Poltype");
                String address=rs.getString("Address");
                String cusName=rs.getString("cusname");
                String polName=rs.getString("polName");
                 String polAmount=String.valueOf(rs.getDouble("polAmount"));
                String polTerm=String.valueOf(rs.getInt("polterm"));
                String famount=String.valueOf(rs.getDouble("fAmount"));
                String aTerm=String.valueOf(rs.getInt("aterms"));
                String currAmount=String.valueOf(rs.getDouble("currntAmount"));
                String regDate=String.valueOf(rs.getDate("regDate"));
                 String endDate=String.valueOf(rs.getDate("endDate"));

                String tbData[] = {nic,aid,poltype,address,cusName,polName,polAmount,polTerm,famount,aTerm,currAmount,regDate,endDate};

                DefaultTableModel tblModel = (DefaultTableModel)jTableCusDetails.getModel();

                tblModel.addRow(tbData);

            }
        
            
    
        } catch (SQLException ex) {
            Logger.getLogger(AgentView.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
       
        
       
    }//GEN-LAST:event_jLabelShowData1MouseClicked

    private void jLabelShowData1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelShowData1MouseEntered
        // TODO add your handling code here:
        jLabelShowData1.setForeground(Color.gray);
    }//GEN-LAST:event_jLabelShowData1MouseEntered

    private void jLabelShowData1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelShowData1MouseExited
        // TODO add your handling code here:
        jLabelShowData1.setForeground(Color.white);
    }//GEN-LAST:event_jLabelShowData1MouseExited

    private void jTextFieldSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearch1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelShowData;
    private javax.swing.JLabel jLabelShowData1;
    private javax.swing.JLabel jLabeldate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCusDetails;
    private javax.swing.JTable jTableCusPayDetails;
    private javax.swing.JTextField jTextFieldAgentId;
    private javax.swing.JTextField jTextFieldBonusRate1;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldSearch1;
    private javax.swing.JTextField jTextFieldbonusPeriod1;
    private javax.swing.JTextField jTextFieldfaceAmount1;
    private javax.swing.JTextField jTextFieldfname10;
    private javax.swing.JTextField jTextFieldfname11;
    private javax.swing.JTextField jTextFieldfname12;
    private javax.swing.JTextField jTextFieldfname13;
    private javax.swing.JTextField jTextFieldfname14;
    private javax.swing.JTextField jTextFieldfname15;
    private javax.swing.JTextField jTextFieldfname5;
    private javax.swing.JTextField jTextFieldfname9;
    private javax.swing.JTextField jTextFieldinterest1;
    private javax.swing.JTextField jTextFieldpolAmount1;
    private javax.swing.JTextField jTextFieldpolName1;
    private javax.swing.JTextField jTextFieldpolTerm1;
    // End of variables declaration//GEN-END:variables
}
