/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package insurance;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author T-PC
 */
public class CustomerPolicy extends javax.swing.JFrame {

    /**
     * Creates new form CustomerPolicy
     */
    Connection conn = null;
    PreparedStatement pst = null;
   
    ResultSet rs = null;
    public CustomerPolicy() {
        initComponents();
        conn=dbConnection.ConnecrDb();
        showDate();
        showTime();
    }
      
    void showDate(){
    Date d =new Date();
    SimpleDateFormat a = new SimpleDateFormat("yyyy/MM/dd");
    jLabeldate.setText(a.format(d));
    
    
    }
    void showTime(){
        new Timer(0, new ActionListener(){
        
            
            public void actionPerformed(ActionEvent e){
             Date d =new Date();
             SimpleDateFormat a = new SimpleDateFormat("hh:mm:ss");
             jLabeltime.setText(a.format(d));
    
            }
        
        
        }).start();
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldpolID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAgentId = new javax.swing.JTextField();
        jTextFieldpolType = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNominee = new javax.swing.JTextField();
        jTextFieldrelation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldAdress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtoncpolCreate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldcusNic = new javax.swing.JTextField();
        jLabelagentSearch = new javax.swing.JLabel();
        jLabelnicSearch = new javax.swing.JLabel();
        jLabelpolSearch = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldcusName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldpolName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldpolAmount = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldpolTerm = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldfaceAmount = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldinterest = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldbonusPeriod = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldBonusRate = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldfname5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldfname9 = new javax.swing.JTextField();
        jTextFieldfname10 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldfname11 = new javax.swing.JTextField();
        jTextFieldfname12 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldfname13 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldfname14 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextFieldfname15 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldpolName1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldpolAmount1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldpolTerm1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextFieldfaceAmount1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldinterest1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldbonusPeriod1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextFieldBonusRate1 = new javax.swing.JTextField();
        jTextFieldAgentName = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextFieldpolaTerm = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabeldate = new javax.swing.JLabel();
        jTextFieldpolEndDate = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabeltime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 153, 153));

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinMouseExited(evt);
            }
        });

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Policy: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMin)
                            .addComponent(jLabelClose))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Policy ID  :");

        jTextFieldpolID.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldpolID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldpolID.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Agent  ID      :");

        jTextFieldAgentId.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldAgentId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAgentId.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldpolType.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldpolType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldpolType.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Policy Type :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nominee   :");

        jTextFieldNominee.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldNominee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNominee.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldrelation.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldrelation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldrelation.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Relation  :");

        jTextFieldAdress.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldAdress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAdress.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Address  :");

        jButtoncpolCreate.setBackground(new java.awt.Color(0, 139, 195));
        jButtoncpolCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtoncpolCreate.setForeground(new java.awt.Color(255, 255, 255));
        jButtoncpolCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Create.png"))); // NOI18N
        jButtoncpolCreate.setText("Create");
        jButtoncpolCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncpolCreateActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cancel.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Customer NIC");

        jTextFieldcusNic.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldcusNic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldcusNic.setForeground(new java.awt.Color(255, 255, 255));

        jLabelagentSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Finduser.png"))); // NOI18N
        jLabelagentSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelagentSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelagentSearchMouseClicked(evt);
            }
        });

        jLabelnicSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Finduser.png"))); // NOI18N
        jLabelnicSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelnicSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelnicSearchMouseClicked(evt);
            }
        });

        jLabelpolSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Finduser.png"))); // NOI18N
        jLabelpolSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelpolSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelpolSearchMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Customer Name");

        jTextFieldcusName.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldcusName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldcusName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Policy Name:");

        jTextFieldpolName.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldpolName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldpolName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Policy Amount:");

        jTextFieldpolAmount.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldpolAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldpolAmount.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Policy Term:");

        jTextFieldpolTerm.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldpolTerm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldpolTerm.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Face Amount   :");

        jTextFieldfaceAmount.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfaceAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfaceAmount.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Interest   :");

        jTextFieldinterest.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldinterest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldinterest.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Bonus Period  :");

        jTextFieldbonusPeriod.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldbonusPeriod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldbonusPeriod.setForeground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Bonus Rate  :");

        jTextFieldBonusRate.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldBonusRate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBonusRate.setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(44, 62, 80));
        jPanel5.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Policy ID  :");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(460, 40, 90, 17);

        jTextFieldfname5.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname5);
        jTextFieldfname5.setBounds(560, 40, 150, 23);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Agent  ID      :");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(770, 40, 100, 17);

        jTextFieldfname9.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname9);
        jTextFieldfname9.setBounds(880, 40, 150, 23);

        jTextFieldfname10.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname10);
        jTextFieldfname10.setBounds(560, 110, 160, 23);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Policy Type :");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(440, 110, 100, 17);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Nominee   :");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(120, 170, 110, 17);

        jTextFieldfname11.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname11);
        jTextFieldfname11.setBounds(250, 170, 150, 23);

        jTextFieldfname12.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname12);
        jTextFieldfname12.setBounds(250, 230, 150, 23);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Relation  :");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(120, 230, 110, 17);

        jTextFieldfname13.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname13);
        jTextFieldfname13.setBounds(250, 300, 150, 23);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Address  :");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(120, 300, 100, 17);

        jButton3.setBackground(new java.awt.Color(0, 139, 195));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Create");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(282, 435, 79, 25);

        jButton4.setBackground(new java.awt.Color(255, 51, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Cancel");
        jPanel5.add(jButton4);
        jButton4.setBounds(134, 435, 77, 25);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Customer NIC");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(99, 42, 124, 17);

        jTextFieldfname14.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname14);
        jTextFieldfname14.setBounds(227, 39, 150, 23);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Finduser.png"))); // NOI18N
        jPanel5.add(jLabel27);
        jLabel27.setBounds(1040, 40, 30, 30);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Finduser.png"))); // NOI18N
        jPanel5.add(jLabel28);
        jLabel28.setBounds(395, 32, 30, 30);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Finduser.png"))); // NOI18N
        jPanel5.add(jLabel29);
        jLabel29.setBounds(730, 30, 30, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Customer Name");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(120, 110, 124, 17);

        jTextFieldfname15.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfname15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfname15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfname15);
        jTextFieldfname15.setBounds(250, 110, 150, 23);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Policy Name:");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(440, 150, 88, 17);

        jTextFieldpolName1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldpolName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldpolName1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldpolName1);
        jTextFieldpolName1.setBounds(560, 150, 160, 23);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Policy Amount:");
        jPanel5.add(jLabel32);
        jLabel32.setBounds(440, 230, 130, 17);

        jTextFieldpolAmount1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldpolAmount1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldpolAmount1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldpolAmount1);
        jTextFieldpolAmount1.setBounds(560, 190, 160, 23);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Policy Term:");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(440, 190, 84, 17);

        jTextFieldpolTerm1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldpolTerm1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldpolTerm1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldpolTerm1);
        jTextFieldpolTerm1.setBounds(560, 230, 160, 23);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Face Amount   :");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(440, 270, 108, 17);

        jTextFieldfaceAmount1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldfaceAmount1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldfaceAmount1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldfaceAmount1);
        jTextFieldfaceAmount1.setBounds(560, 270, 160, 23);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Interest   :");
        jPanel5.add(jLabel35);
        jLabel35.setBounds(440, 310, 74, 17);

        jTextFieldinterest1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldinterest1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldinterest1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldinterest1);
        jTextFieldinterest1.setBounds(560, 310, 160, 23);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Bonus Period  :");
        jPanel5.add(jLabel36);
        jLabel36.setBounds(440, 350, 105, 17);

        jTextFieldbonusPeriod1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldbonusPeriod1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldbonusPeriod1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldbonusPeriod1);
        jTextFieldbonusPeriod1.setBounds(560, 350, 160, 23);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Bonus Rate  :");
        jPanel5.add(jLabel37);
        jLabel37.setBounds(440, 390, 93, 17);

        jTextFieldBonusRate1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldBonusRate1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBonusRate1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jTextFieldBonusRate1);
        jTextFieldBonusRate1.setBounds(560, 390, 160, 23);

        jTextFieldAgentName.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldAgentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAgentName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Agent Name :");

        jTextFieldpolaTerm.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldpolaTerm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldpolaTerm.setForeground(new java.awt.Color(255, 255, 255));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Enter  Term :");

        jLabeldate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabeldate.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldpolEndDate.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldpolEndDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldpolEndDate.setForeground(new java.awt.Color(255, 255, 255));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Enter  policyEnd Date :");

        jLabeltime.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabeltime.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/keep-calm-customer-is-king.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jTextFieldNominee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(jLabel15)
                            .addGap(36, 36, 36)
                            .addComponent(jTextFieldpolTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jTextFieldcusName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(32, 32, 32)
                                        .addComponent(jTextFieldpolName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(jTextFieldpolAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jTextFieldcusNic, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelnicSearch))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabeldate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabeltime, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldpolID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabelpolSearch)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jTextFieldAgentId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelagentSearch)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(440, 440, 440)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(10, 10, 10)
                                    .addComponent(jTextFieldfaceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(90, 90, 90)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(59, 59, 59)
                            .addComponent(jTextFieldpolaTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jTextFieldrelation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(jTextFieldpolType, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldbonusPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(44, 44, 44)
                                                .addComponent(jTextFieldinterest, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(90, 90, 90)
                                                .addComponent(jLabel40))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(22, 22, 22)
                                                .addComponent(jTextFieldBonusRate, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(60, 60, 60)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtoncpolCreate)
                                    .addComponent(jTextFieldpolEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jTextFieldcusNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelnicSearch)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTextFieldpolID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelpolSearch))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jTextFieldAgentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelagentSearch)))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jTextFieldcusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel13))
                            .addComponent(jTextFieldpolName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldpolAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel14))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(jTextFieldAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(jTextFieldNominee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jTextFieldpolTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldrelation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(jTextFieldpolType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTextFieldfaceAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel39))
                    .addComponent(jTextFieldpolaTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel17))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jTextFieldinterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel40))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jTextFieldpolEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jTextFieldBonusRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2)
                                .addComponent(jButtoncpolCreate))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabeltime, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(jLabeldate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextFieldbonusPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODOdd your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jButtoncpolCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncpolCreateActionPerformed
        // TODO add your handling code here:
                try {
            // TODO add your handling code here:
            String nic=jTextFieldcusNic.getText();
            String pid=jTextFieldpolID.getText();
            String aid=jTextFieldAgentId.getText();
            String polType=jTextFieldpolType.getText();
            String relation=jTextFieldrelation.getText();
            String address=jTextFieldAdress.getText();
            String cusName=jTextFieldcusName.getText();
            String nominee=jTextFieldNominee.getText();
            String polName=jTextFieldpolName.getText();
            String polamount =jTextFieldpolAmount.getText();
            String polterm=jTextFieldpolTerm.getText();
            String famount=jTextFieldfaceAmount.getText();
            String interest=jTextFieldinterest.getText();
            String bPeriod=jTextFieldbonusPeriod.getText();
            String bRate=jTextFieldBonusRate.getText();
            String agentname=jTextFieldAgentName.getText();
            String aterm=jTextFieldpolaTerm.getText();
            String regDate =jLabeldate.getText();
            String endDate=jTextFieldpolEndDate.getText();
            
            
       
            
            String query="insert into CustomerPolicy(nic,pID,aId,Poltype,relation,Address,cusname,nominee,polName,polAmount,polterm,fAmount,interest,BonusPeriod,BonusRate,agentName,aterms,regDate,endDate) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(query);
            pst.setString(1, nic);
            pst.setString(2,pid);
            pst.setString(3, aid);
            pst.setString(4, polType);
            pst.setString(5, relation);
            pst.setString(6, address);
            pst.setString(7, cusName);
            pst.setString(8, nominee);
            pst.setString(9, polName);
            pst.setString(10, polamount);
            pst.setString(11, polterm);
            pst.setString(12, famount);
            pst.setString(13, interest);
            pst.setString(14, bPeriod);
            pst.setString(15, bRate);
            pst.setString(16, agentname);
            pst.setString(17, aterm);
            pst.setString(18, regDate);
            pst.setString(19, endDate);
           
           
           
            pst.executeUpdate();
            
            
            JOptionPane.showMessageDialog(this, "Policy add Success");
            
           
          
           
           
        }
           
           
           
          
        catch (SQLException ex) {
            Logger.getLogger(CustomerReg.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "User Cannot have two policies Enter valid NIC");
            
        }
    }//GEN-LAST:event_jButtoncpolCreateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabelnicSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelnicSearchMouseClicked
        try {
            // TODO add your handling code here:
            String query="select*from Customer where nic=?";
            String search =jTextFieldcusNic.getText();
            
            pst=conn.prepareStatement(query);
            pst.setString(1,search);
            rs =pst.executeQuery();
            
            if(rs.next()== false){
                
                
                JOptionPane.showMessageDialog(this, "Customer not found");
               
               
                
            }else{
                String mName=rs.getString("name");
                jTextFieldcusName.setText(mName);
                String address=rs.getString("Address");
                jTextFieldAdress.setText(address);
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerPolicy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelnicSearchMouseClicked

    private void jLabelpolSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpolSearchMouseClicked
        // TODO add your handling code here:
       String query="select*from Policy where pID=?";
        String search =jTextFieldpolID.getText();

        try {
            pst=conn.prepareStatement(query);
            pst.setString(1,search);
            rs =pst.executeQuery();
            if(rs.next()==false){
                
                 JOptionPane.showMessageDialog(this, "Policy not found Enter Valid ID");
                 
                 
            }else{
                String mName=rs.getString("pName");
                jTextFieldpolName.setText(mName);
                String mfarName=rs.getString("pAmount");
                jTextFieldpolAmount.setText(mfarName);
                String mTerm=rs.getString("PTerm");
                jTextFieldpolTerm.setText(mTerm);
                String mType=rs.getString("ptype");
                jTextFieldpolType.setText(mType);
                String mAmount=rs.getString("fAmount");
                jTextFieldfaceAmount.setText(mAmount);
                String mInterest=rs.getString("interest");
                jTextFieldinterest.setText( mInterest);
                String mbPeriod=rs.getString("bonusPeriod");
                jTextFieldbonusPeriod.setText(mbPeriod);
                String mbRate=rs.getString("bonusRate");
                jTextFieldBonusRate.setText(mbRate);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PolicyMod.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelpolSearchMouseClicked

    private void jLabelagentSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelagentSearchMouseClicked
        // TODO add your handling code here:
        String query="select*from Agent where aId=?";
        String search =jTextFieldAgentId.getText();
        try {
            // TODO add your handling code here:
            
            
            pst=conn.prepareStatement(query);
            pst.setString(1,search);
            rs =pst.executeQuery();
            
            if(rs.next()==false){
                
               JOptionPane.showMessageDialog(this, "Agent not found Enter Valid ID");
               
            }else{
                String aName=rs.getString("aname");
                jTextFieldAgentName.setText(aName);
                
               
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(CustomerPolicy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelagentSearchMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menuadmin reg = new Menuadmin();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        // TODO add your handling code here:
        jLabelClose.setForeground(Color.RED);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        // TODO add your handling code here:
          jLabelClose.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseEntered
        // TODO add your handling code here:
         jLabelMin.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelMinMouseEntered

    private void jLabelMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseExited
        // TODO add your handling code here:
         jLabelMin.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelMinMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPolicy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPolicy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtoncpolCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelagentSearch;
    private javax.swing.JLabel jLabeldate;
    private javax.swing.JLabel jLabelnicSearch;
    private javax.swing.JLabel jLabelpolSearch;
    private javax.swing.JLabel jLabeltime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextFieldAdress;
    private javax.swing.JTextField jTextFieldAgentId;
    private javax.swing.JTextField jTextFieldAgentName;
    private javax.swing.JTextField jTextFieldBonusRate;
    private javax.swing.JTextField jTextFieldBonusRate1;
    private javax.swing.JTextField jTextFieldNominee;
    private javax.swing.JTextField jTextFieldbonusPeriod;
    private javax.swing.JTextField jTextFieldbonusPeriod1;
    private javax.swing.JTextField jTextFieldcusName;
    private javax.swing.JTextField jTextFieldcusNic;
    private javax.swing.JTextField jTextFieldfaceAmount;
    private javax.swing.JTextField jTextFieldfaceAmount1;
    private javax.swing.JTextField jTextFieldfname10;
    private javax.swing.JTextField jTextFieldfname11;
    private javax.swing.JTextField jTextFieldfname12;
    private javax.swing.JTextField jTextFieldfname13;
    private javax.swing.JTextField jTextFieldfname14;
    private javax.swing.JTextField jTextFieldfname15;
    private javax.swing.JTextField jTextFieldfname5;
    private javax.swing.JTextField jTextFieldfname9;
    private javax.swing.JTextField jTextFieldinterest;
    private javax.swing.JTextField jTextFieldinterest1;
    private javax.swing.JTextField jTextFieldpolAmount;
    private javax.swing.JTextField jTextFieldpolAmount1;
    private javax.swing.JTextField jTextFieldpolEndDate;
    private javax.swing.JTextField jTextFieldpolID;
    private javax.swing.JTextField jTextFieldpolName;
    private javax.swing.JTextField jTextFieldpolName1;
    private javax.swing.JTextField jTextFieldpolTerm;
    private javax.swing.JTextField jTextFieldpolTerm1;
    private javax.swing.JTextField jTextFieldpolType;
    private javax.swing.JTextField jTextFieldpolaTerm;
    private javax.swing.JTextField jTextFieldrelation;
    // End of variables declaration//GEN-END:variables
}
