/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package insurance;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JFrame;

/**
 *
 * @author T-PC
 */
public class Menuadmin extends javax.swing.JFrame {

    /**
     * Creates new form Menuadmin
     */
    public Menuadmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelcreg = new javax.swing.JLabel();
        jLabelcmod = new javax.swing.JLabel();
        jLabelcpolr = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelpolReg = new javax.swing.JLabel();
        jLabelpolMod = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelagentR = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelPayment1 = new javax.swing.JLabel();
        jLabelcreg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 153, 153));

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinMouseExited(evt);
            }
        });

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Admin ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMin)
                            .addComponent(jLabelClose)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(44, 62, 80));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Customer.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer");

        jLabelcreg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelcreg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcreg.setText("Customer Registration");
        jLabelcreg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabelcreg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelcreg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcregMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelcregMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelcregMouseExited(evt);
            }
        });

        jLabelcmod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelcmod.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcmod.setText("Customer Modificaion");
        jLabelcmod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabelcmod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelcmod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcmodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelcmodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelcmodMouseExited(evt);
            }
        });

        jLabelcpolr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelcpolr.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcpolr.setText("Customer Policy Registration");
        jLabelcpolr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabelcpolr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelcpolr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcpolrMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelcpolrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelcpolrMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelcmod)
                    .addComponent(jLabelcreg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabelcpolr)
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(56, 56, 56)
                .addComponent(jLabelcreg)
                .addGap(26, 26, 26)
                .addComponent(jLabelcmod)
                .addGap(18, 18, 18)
                .addComponent(jLabelcpolr)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5);
        jPanel5.setBounds(10, 140, 230, 290);

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Policy.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Policy");

        jLabelpolReg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelpolReg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelpolReg.setText("Policy Registration");
        jLabelpolReg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabelpolReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelpolReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelpolRegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelpolRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelpolRegMouseExited(evt);
            }
        });

        jLabelpolMod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelpolMod.setForeground(new java.awt.Color(255, 255, 255));
        jLabelpolMod.setText("Policy Modification");
        jLabelpolMod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabelpolMod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelpolMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelpolModMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelpolModMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelpolModMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelpolReg)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelpolMod)
                            .addGap(47, 47, 47))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7))
                            .addGap(93, 93, 93)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(61, 61, 61)
                .addComponent(jLabelpolReg)
                .addGap(36, 36, 36)
                .addComponent(jLabelpolMod)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3);
        jPanel3.setBounds(520, 140, 244, 290);

        jPanel6.setBackground(new java.awt.Color(44, 62, 80));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/agent.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Agent");

        jLabelagentR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelagentR.setForeground(new java.awt.Color(255, 255, 255));
        jLabelagentR.setText("Agent Registration");
        jLabelagentR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabelagentR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelagentR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelagentRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelagentRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelagentRMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabelagentR)
                        .addGap(61, 61, 61))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(53, 53, 53)
                .addComponent(jLabelagentR)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6);
        jPanel6.setBounds(260, 140, 250, 290);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Background.jpg"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 90, 750, 370);

        jLabel10.setFont(new java.awt.Font("Niconne", 1, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Bulb.png"))); // NOI18N
        jLabel10.setText("  Start Your Day With a Smile");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(420, 10, 350, 50);

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("..........Start Your Life With Our Best Policies...................");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(180, 470, 400, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-website-50.png"))); // NOI18N
        jLabel11.setText("Our Web");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jPanel4.add(jLabel11);
        jLabel11.setBounds(130, 10, 102, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-new-post-50.png"))); // NOI18N
        jLabel12.setText("Send Mail");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPanel4.add(jLabel12);
        jLabel12.setBounds(10, 10, 110, 50);

        jLabelPayment1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPayment1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPayment1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Payment.png"))); // NOI18N
        jLabelPayment1.setText("Payment");
        jLabelPayment1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPayment1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPayment1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPayment1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPayment1MouseExited(evt);
            }
        });
        jPanel4.add(jLabelPayment1);
        jLabelPayment1.setBounds(240, 10, 120, 50);

        jLabelcreg1.setBackground(new java.awt.Color(0, 204, 204));
        jLabelcreg1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelcreg1.setForeground(new java.awt.Color(102, 255, 255));
        jLabelcreg1.setText("Details?");
        jLabelcreg1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabelcreg1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelcreg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcreg1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelcreg1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelcreg1MouseExited(evt);
            }
        });
        jPanel4.add(jLabelcreg1);
        jLabelcreg1.setBounds(670, 480, 80, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
       this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelcregMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcregMouseClicked
        // TODO add your handling code here:
        CustomerReg reg = new CustomerReg();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jLabelcregMouseClicked

    private void jLabelcmodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcmodMouseClicked
        // TODO add your handling code here:
        CustomerMod mod = new CustomerMod();
        mod.setVisible(true);
        mod.pack();
        mod.setLocationRelativeTo(null);
        mod.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelcmodMouseClicked

    private void jLabelcpolrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcpolrMouseClicked
        // TODO add your handling code here:
        CustomerPolicy policy=new CustomerPolicy();
        policy.setVisible(true);
        policy.pack();
        policy.setLocationRelativeTo(null);
        policy.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelcpolrMouseClicked

    private void jLabelagentRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelagentRMouseClicked
        // TODO add your handling code here:
        AgentReg aReg=new AgentReg();
        aReg.setVisible(true);
        aReg.pack();
        aReg.setLocationRelativeTo(null);
        aReg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelagentRMouseClicked

    private void jLabelpolRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpolRegMouseClicked
        // TODO add your handling code here:
        PolicyReg pReg=new PolicyReg();
        pReg.setVisible(true);
        pReg.pack();
        pReg.setLocationRelativeTo(null);
        pReg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelpolRegMouseClicked

    private void jLabelpolModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpolModMouseClicked
        // TODO add your handling code here:
        PolicyMod pMod=new PolicyMod();
        pMod.setVisible(true);
        pMod.pack();
        pMod.setLocationRelativeTo(null);
        pMod.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelpolModMouseClicked

    private void jLabelcregMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcregMouseEntered
        // TODO add your handling code here:
        jLabelcreg.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelcregMouseEntered

    private void jLabelcregMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcregMouseExited
        // TODO add your handling code here:
         jLabelcreg.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelcregMouseExited

    private void jLabelcmodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcmodMouseEntered
        // TODO add your handling code here:
         jLabelcmod.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelcmodMouseEntered

    private void jLabelcmodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcmodMouseExited
        // TODO add your handling code here:
         jLabelcmod.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelcmodMouseExited

    private void jLabelcpolrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcpolrMouseEntered
        // TODO add your handling code here:
         jLabelcpolr.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelcpolrMouseEntered

    private void jLabelcpolrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcpolrMouseExited
        // TODO add your handling code here:
         jLabelcpolr.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelcpolrMouseExited

    private void jLabelagentRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelagentRMouseEntered
        // TODO add your handling code here:
         jLabelagentR.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelagentRMouseEntered

    private void jLabelpolRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpolRegMouseEntered
        // TODO add your handling code here:
         jLabelpolReg.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelpolRegMouseEntered

    private void jLabelpolRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpolRegMouseExited
        // TODO add your handling code here:
         jLabelpolReg.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelpolRegMouseExited

    private void jLabelpolModMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpolModMouseEntered
        // TODO add your handling code here:
         jLabelpolMod.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelpolModMouseEntered

    private void jLabelpolModMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelpolModMouseExited
        // TODO add your handling code here:
         jLabelpolMod.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelpolModMouseExited

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        // TODO add your handling code here:
        jLabelClose.setForeground(Color.RED);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        // TODO add your handling code here:
        jLabelClose.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseEntered
        // TODO add your handling code here:
           jLabelMin.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabelMinMouseEntered

    private void jLabelMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseExited
        // TODO add your handling code here:
        jLabelMin.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelMinMouseExited

    private void jLabelagentRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelagentRMouseExited
        // TODO add your handling code here:
         jLabelagentR.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabelagentRMouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        Desktop browser=Desktop.getDesktop();
        try{
        browser.browse(new URI("http://www.google.com/"));
        }
        catch(IOException err){
        
        }
        catch(URISyntaxException err){
        
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        Mail mail=new Mail();
        mail.setVisible(true);
        mail.pack();
        mail.setLocationRelativeTo(null);
        mail.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
         jLabel11.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
          jLabel11.setForeground(Color.white);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
         jLabel12.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
         jLabel12.setForeground(Color.white);
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabelPayment1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPayment1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPayment1MouseClicked

    private void jLabelPayment1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPayment1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPayment1MouseEntered

    private void jLabelPayment1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPayment1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPayment1MouseExited

    private void jLabelcreg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcreg1MouseClicked
        // TODO add your handling code here:
        Details de=new Details();
        de.setVisible(true);
        de.pack();
        de.setLocationRelativeTo(null);
        de.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelcreg1MouseClicked

    private void jLabelcreg1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcreg1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelcreg1MouseEntered

    private void jLabelcreg1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcreg1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelcreg1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelPayment1;
    private javax.swing.JLabel jLabelagentR;
    private javax.swing.JLabel jLabelcmod;
    private javax.swing.JLabel jLabelcpolr;
    private javax.swing.JLabel jLabelcreg;
    private javax.swing.JLabel jLabelcreg1;
    private javax.swing.JLabel jLabelpolMod;
    private javax.swing.JLabel jLabelpolReg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
